### ISSUE TITLE
kotlin.Result<T> mocking is not working as expected

### ISSUE THREAD

**Issue by siboxd** [mockk/mockk#645]
### Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version (checked on `1.10.6` and `1.11.0`)
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

### Expected Behavior

I expect that mockk treats `kotlin.Result<T>` class as other classes

### Current Behavior

It seems that it is unnecessary wrapping any `Result<T>` return type to another `Result.success` instance making even a basic test fail.

### Failure Information (for bugs)

I have no useful information at this time... I'll add if I find useful info.

#### Steps to Reproduce

Let's consider this piece of code:

```kotlin
    class Data

    interface MyInterface {
        fun getData(): Result<Data>
    }
```

Now I'm gonna test, with a mockk of `MyInterface`, that it returns the instance of `Data` class wrapped in a `Result.success` instance:

```kotlin
    @Test
    fun testWithBug() {
        val myDataResult = Result.success(Data())
        val myInterface = mockk<MyInterface> {
            every { getData() } returns myDataResult
        }

        assertSame(myDataResult, myInterface.getData())
    }
``` 

This test fails with:
```
java.lang.AssertionError: expected same:<Success(com.my.test.MyTest$Data@6e0cff20)> was not:<Success(Success(com.my.test.MyTest$Data@6e0cff20))>
Expected :Success(com.my.test.MyTest$Data@6e0cff20)
Actual   :Success(Success(com.my.test.MyTest$Data@6e0cff20))
```

But there's no code wrapping the `Data()` in two successes... from where does it come?

The thing is that it's a problem of the `Result` class because if you do this, the test passes:

```kotlin
    class Data

    interface MyInterface {
        fun getData(): Data
    }

    @Test
    fun testWithBug() {
        val myDataResult = Data()
        val myInterface = mockk<MyInterface> {
            every { getData() } returns myDataResult
        }

        assertSame(myDataResult, myInterface.getData())
    }
``` 

#### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* MockK version: 1.10.6 and 1.11.0
* OS: macOS 10.15.7
* Kotlin version: 1.5.10
* JDK version: 1.8.0_282
* JUnit version: 4.13.2
* Type of test: unit test

#### Minimal reproducible code (the gist of this issue)

```kotlin
// -----------------------[ GRADLE DEFINITIONS ] -----------------------
dependencies {
    testImplementation "junit:junit:4.13.2"
    testImplementation "io.mockk:mockk:1.11.0"
}
// -----------------------[ YOUR CODE STARTS HERE ] -----------------------
package com.my.test

import io.mockk.every
import io.mockk.mockk
import org.junit.Assert.assertSame
import org.junit.Test

class MyTest {
    class Data

    interface MyInterface {
        fun getData(): Result<Data>
    }

    @Test
    fun testWithBug() {
        val myDataResult = Result.success(Data())
        val myInterface = mockk<MyInterface> {
            every { getData() } returns myDataResult
        }

        assertSame(myDataResult, myInterface.getData())
    }
}
// -----------------------[ YOUR CODE ENDS HERE ] -----------------------
```

**Comment by deadeyye** [comment]
This is known problem, it should be solved by this https://github.com/mockk/mockk/pull/633
Now we just need to wait for release.

**Comment by siboxd** [comment]
I've seen the new version 1.12.0 of Mockk and I gave it a try.

For some reason the `assertSame` still gives an assertion error...

Have you tried my use case with the new version 1.12.0?

Thanks

**Comment by b22n** [comment]
It is reproduced in 1.12.0 (kotlin 1.5.21 ~ 1.5.31)

**Comment by nuhkoca** [comment]
This is still occurring in 1.12.0

**Comment by milken** [comment]
I can confirm it still happens for `value class` in 1.12.2.
I'm staying on 1.10.2 until resolved :(

**Comment by siboxd** [comment]
Any news on this? Could' you put the important label?

**Comment by siboxd** [comment]
The issue is still present with: kotlin `1.6.21` and mockk `1.12.4`

The `assertSame` still gives an assertion error...

Any news on this issue? Could you put the `important` label?

**Comment by siboxd** [comment]
Any news on this? Could you put the important label?

**Comment by behnawwm** [comment]
It's still happening in 1.13.8 and Kotlin 1.9

**Comment by aditya-dodda** [comment]
Same issue.

**Comment by alfietapping** [comment]
Still happening on 1.13.16

**Comment by yanosDev** [comment]
Seems like 1.13.16 reintroduced the issue. For me on .14 its working fine
